language: cpp
os:
  - linux

dist: focal

services:
  - docker

env:
  global:
  - PYTHON_BLOCKLIST="cp27 pp27 cp35"

jobs:
  include:
    - arch: amd64
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686
           PRE_CMD=linux32
           PLAT=manylinux2010_i686
    - arch: amd64
      env: DOCKER_IMAGE=pypywheels/manylinux2010-pypy_x86_64
           PLAT=manylinux2010_x86_64
    - arch: arm64-graviton2
      group: edge
      virt: vm
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
           PLAT=manylinux2014_aarch64
    - arch: ppc64le
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_ppc64le
           PLAT=manylinux2014_ppc64le
    # - arch: s390x
    #   env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_s390x
    #        PLAT=manylinux2014_s390x
  # Travis output hangs when lxd virt is used and secret env vars are set
  allow_failures:
    - if: branch=master
      arch: ppc64le

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PYTHON_BLOCKLIST="$PYTHON_BLOCKLIST" -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels.sh
  - ls -lah wheelhouse/
  # ARTIFACT_URL_BASE=https://some.cloud.com/public.php/webdav/
  # ARTIFACT_USER=share_token
  - |
    if [[ -v ARTIFACT_URL_BASE ]]; then
      cd wheelhouse

      export ARTIFACT_URL="${ARTIFACT_URL_BASE}/${TRAVIS_BUILD_NUMBER}_${TRAVIS_COMMIT:0:7}"
      export ARTIFACT_CURL_OPTS="-u '${ARTIFACT_USER}:${ARTIFACT_PASS}' -H 'X-Requested-With: XMLHttpRequest'"

      if [ "404" = "$(eval curl -o /dev/null -s -w '%{http_code}' ${ARTIFACT_CURL_OPTS} -X PROPFIND ${ARTIFACT_URL})" ]; then
        eval curl "${ARTIFACT_CURL_OPTS}" -X MKCOL "${ARTIFACT_URL}"
      fi
      for whl in *.whl; do
        echo "Pushing artifact ${whl} ..."
        eval curl -T ${whl} ${ARTIFACT_CURL_OPTS} ${ARTIFACT_URL}/${whl}
      done
    fi

