language: cpp
os:
  - linux

dist: bionic

services:
  - docker

jobs:
  include:
    - arch: amd64
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686
           PRE_CMD=linux32
           PLAT=manylinux2014_i686
    - arch: amd64
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
           PLAT=manylinux2014_x86_64
    - arch: amd64
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
           PLAT=manylinux2014_aarch64
           QEMU_USER=YES
    - arch: ppc64le
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_ppc64le
           PLAT=manylinux2014_ppc64le
    # - arch: s390x
    #   env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_s390x
    #        PLAT=manylinux2014_s390x  
  # Travis output hangs on LXD (only available option on some platforms) with set secret env vars
  allow_failures:
    - if: branch=master
      arch: arm64
    - if: branch=master
      arch: ppc64le

install:
  - docker pull $DOCKER_IMAGE
  - |
    if [[ -v QEMU_USER ]]; then
      apt-get update
      apt-get install -y --no-install-recommends binfmt-support
      git clone --depth 1 --branch v5.1.0 https://github.com/qemu/qemu.git
      mkdir qemu/build
      cd qemu/build
      ../configure --static --target-list=aarch64-linux-user,ppc64le-linux-user
      make -j$(nproc)
      make recurse-install
      ../scripts/qemu-binfmt-conf.sh
      export MOUNT_BIN="-v /usr/local/bin/qemu-aarch64:/usr/local/bin/qemu-aarch64:ro -v /usr/local/bin/qemu-ppc64le:/usr/local/bin/qemu-ppc64le:ro"
      cd ../..
      rm -rf qemu
    fi

script:
  - echo $MOUNT_BIN
  - docker run --rm -e PLAT=$PLAT $MOUNT_BIN -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels.sh
  - ls -lah wheelhouse/
  # ARTIFACT_URL_BASE=https://some.cloud.com/public.php/webdav/
  # ARTIFACT_USER=share_token
  - |
    if [[ -v ARTIFACT_URL_BASE ]]; then
      cd wheelhouse

      export ARTIFACT_URL="${ARTIFACT_URL_BASE}/${TRAVIS_BUILD_NUMBER}_${TRAVIS_COMMIT:0:7}"
      export ARTIFACT_CURL_OPTS="-u '${ARTIFACT_USER}:${ARTIFACT_PASS}' -H 'X-Requested-With: XMLHttpRequest'"

      if [ "404" = "$(eval curl -o /dev/null -s -w '%{http_code}' ${ARTIFACT_CURL_OPTS} -X PROPFIND ${ARTIFACT_URL})" ]; then
        eval curl "${ARTIFACT_CURL_OPTS}" -X MKCOL "${ARTIFACT_URL}"
      fi
      for whl in *.whl; do
        echo "Pushing artifact ${whl} ..."
        eval curl -T ${whl} ${ARTIFACT_CURL_OPTS} ${ARTIFACT_URL}/${whl}
      done
    fi

