services:
  - docker

matrix:
  include:
    - arch: amd64
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686
           PRE_CMD=linux32
           PLAT=manylinux2014_i686
    - arch: amd64
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
           PLAT=manylinux2014_x86_64
    - arch: arm64
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
           PLAT=manylinux2014_aarch64
    - arch: ppc64le
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_ppc64le
           PLAT=manylinux2014_ppc64le
    # - arch: s390x
    #   env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_s390x
    #        PLAT=manylinux2014_s390x

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels.sh
  - ls -lah wheelhouse/
